// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4dBvO9LLcGsia4wHYjdQCEUES13NMJYU',
    appId: '1:842197612476:web:b3beb97338f79d3e935db9',
    messagingSenderId: '842197612476',
    projectId: 'fir-auth-d54ed',
    authDomain: 'fir-auth-d54ed.firebaseapp.com',
    storageBucket: 'fir-auth-d54ed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9549isoNVfEDDBtorYQtJ7Qcdy70k0N4',
    appId: '1:842197612476:android:fa6d5979c7ccc5ce935db9',
    messagingSenderId: '842197612476',
    projectId: 'fir-auth-d54ed',
    storageBucket: 'fir-auth-d54ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLcJJD9C3qpEuzRkjnBVIQnzqFZiRsV9U',
    appId: '1:842197612476:ios:c0eed2c63f5b1dc1935db9',
    messagingSenderId: '842197612476',
    projectId: 'fir-auth-d54ed',
    storageBucket: 'fir-auth-d54ed.firebasestorage.app',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLcJJD9C3qpEuzRkjnBVIQnzqFZiRsV9U',
    appId: '1:842197612476:ios:c0eed2c63f5b1dc1935db9',
    messagingSenderId: '842197612476',
    projectId: 'fir-auth-d54ed',
    storageBucket: 'fir-auth-d54ed.firebasestorage.app',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4dBvO9LLcGsia4wHYjdQCEUES13NMJYU',
    appId: '1:842197612476:web:1fe575318ac5d16e935db9',
    messagingSenderId: '842197612476',
    projectId: 'fir-auth-d54ed',
    authDomain: 'fir-auth-d54ed.firebaseapp.com',
    storageBucket: 'fir-auth-d54ed.firebasestorage.app',
  );
}
